// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKuQeYxpAurMf_UOmOVCNkryecNibzeY0',
    appId: '1:114548616572:web:49326c2abf82eb815f08f9',
    messagingSenderId: '114548616572',
    projectId: 'eccomerce-a0e85',
    authDomain: 'eccomerce-a0e85.firebaseapp.com',
    storageBucket: 'eccomerce-a0e85.appspot.com',
    measurementId: 'G-QY8039VW5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKlO9m0amdz6fwKiijEfkJo6eEtME2EMY',
    appId: '1:114548616572:android:74018bca638046995f08f9',
    messagingSenderId: '114548616572',
    projectId: 'eccomerce-a0e85',
    storageBucket: 'eccomerce-a0e85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIaNLA5-4t3QZ_EUuM-fF5hoOL2Lmz8qs',
    appId: '1:114548616572:ios:878bf0634176f5405f08f9',
    messagingSenderId: '114548616572',
    projectId: 'eccomerce-a0e85',
    storageBucket: 'eccomerce-a0e85.appspot.com',
    iosBundleId: 'com.example.etradinggradproj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIaNLA5-4t3QZ_EUuM-fF5hoOL2Lmz8qs',
    appId: '1:114548616572:ios:878bf0634176f5405f08f9',
    messagingSenderId: '114548616572',
    projectId: 'eccomerce-a0e85',
    storageBucket: 'eccomerce-a0e85.appspot.com',
    iosBundleId: 'com.example.etradinggradproj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKuQeYxpAurMf_UOmOVCNkryecNibzeY0',
    appId: '1:114548616572:web:0231a1e3d65c0b945f08f9',
    messagingSenderId: '114548616572',
    projectId: 'eccomerce-a0e85',
    authDomain: 'eccomerce-a0e85.firebaseapp.com',
    storageBucket: 'eccomerce-a0e85.appspot.com',
    measurementId: 'G-6WR3W5W0L9',
  );
}
